---
cidr_networks:
  container: 192.168.1.0/24 # 192.168.1.0 - 192.168.1.63

used_ips:
  - "192.168.1.0,192.168.1.24" # lab metal hosts

global_overrides:
  internal_lb_vip_address: 192.168.1.20 #192.168.1.129
  external_lb_vip_address: 192.168.1.20 #192.168.1.129
  management_bridge: "br-mgmt"

  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - neutron_openvswitch_agent
        container_bridge: "br-vlan"
        container_interface: "eth12"
        container_type: "veth"
        type: "vlan"
        range: "102:199"
        net_name: "physnet1"

shared-infra_hosts:
  man1.oslab:
    ip: 192.168.1.20

repo-infra_hosts:
  man1.oslab:
    ip: 192.168.1.20

os-infra_hosts:
  man1.oslab:
    ip: 192.168.1.20

identity_hosts:
  man1.oslab:
    ip: 192.168.1.20

network_hosts:
  man1.oslab:
    ip: 192.168.1.20

compute_hosts:
  comp1.oslab:
    ip: 192.168.1.21
  comp2.oslab:
    ip: 192.168.1.22

# The cinder-api service gets deployed here
storage-infra_hosts:
  man1.oslab:
    ip: 192.168.1.20

# The cinder-volume service gets deployed
storage_hosts:
  man1.oslab:
    ip: 192.168.1.20
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          volume_backend_name: rbd
          rbd_pool: cinder_volumes
          rbd_ceph_conf: /etc/ceph/ceph.conf
          rbd_user: cinder

metering-compute_hosts:
  comp1.oslab:
    ip: 192.168.1.21
  comp2.oslab:
    ip: 192.168.1.22

metering-infra_hosts:
  man1.oslab:
    ip: 192.168.1.20

haproxy_hosts:
  man1.oslab:
    ip: 192.168.1.20

log_hosts:
  man1.oslab:
    ip: 192.168.1.20

